- name: "install epel-release"
  yum:
    name: epel-release
    state: installed

- name: "install nginx"
  yum:
    name: nginx
    state: installed

- name: "ensure that webserver is running"
  service:
    name: "nginx"
    state: started
    enabled: yes
  register: nginx_status

- name: "Debug start"
  template:
    src:  roles/nginx/templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0640
  become: true
  when: nginx_status.state == "started"
  notify:
    - reload nginx
